res_file ='2024-10-13_test.md'
token = "" #"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiZGV2ZWxvcGVyIiwiZmlyc3ROYW1lIjoiUGV0ZXIgUGV0cm92aWNoIiwibGFzdE5hbWUiOiJQZXRyb3YiLCJsb2NhbGl0eSI6ItCV0YHRgdC10L3RgtGD0LrQuDIiLCJyZWdpb24iOiIyNiIsInJlZ2lvbkNvZGUiOiIyNiIsInVzZXJpZCI6IjM4MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiMzgzIiwicm9sZWlkIjoiMTIiLCJwZXJtaXNzaW9ucyI6IlVzZXJzLFJvbGVzLE5ld3MsU3RhdGlzdGljYWxJbmYsUmV0YWlsLE1hcmtldFBhcnRpY2lwYW50cyxNYXJrZXRQYXJ0aWNpcGFudHNWMixSZXBvcnRzLE9yZ2FuaXphdGlvbnMsUmVwb3J0VGVtcGxhdGVzLFJldGFpbCxSZXRhaWwsUmV0YWlsLFJldGFpbCxSZXRhaWwsUmV0YWlsLFJldGFpbCxSZXRhaWwsUmV0YWlsLFJldGFpbCxSZXRhaWwsUmV0YWlsLFJldGFpbCxSZXRhaWwsUmV0YWlsLFJldGFpbCxSZXRhaWwsUmV0YWlsLFJldGFpbCxTdGF0aXN0aWNhbEluZixTdGF0aXN0aWNhbEluZixSZXRhaWwsUmV0YWlsLFJldGFpbCxSZXRhaWwsUmV0YWlsLFJldGFpbCxTdGF0aXN0aWNhbEluZixSZXRhaWwiLCJsaXN0UmVnaW9uQ29kZXMiOiIyNiIsImV4cCI6MTcyODQ4Mjc0MiwiaXNzIjoiQ0FFZ2FpcyIsImF1ZCI6IlVzZXJzIn0.-5nr1Tk3pq7hfk1qJXi91RP3BTzvFp07a4pNvqxzzkI"
requestid =225358
blistRegionCodes = 77
bregionCode = 77
brole = 'developer'
#main_path = "/media/nuanred/backup/repo /test_explorer/save_report/reports"
main_path='/media/nuanred/backup/repo /test_explorer/redmine/2024_10_16/484760/'

sand_token = "Bearer eyJhbGciOiJIUzUxMiJ9.eyJmaXJzdE5hbWUiOiJBdXRvIiwibGFzdE5hbWUiOiJBdXRvIiwicmVnaW9uQ29kZSI6Ijc3Iiwicm9sZSI6ImRldmVsb3BlciIsInBlcm1pc3Npb25zIjoiUmV0YWlsIiwicm9sZWlkIjoiMCIsImxvY2FsaXR5IjoiQXV0byIsImxpc3RSZWdpb25Db2RlcyI6Ijc3IiwicmVnaW9uIjoiQXV0byIsInVzZXJpZCI6IjEyMyJ9.ZLZ8qYylnLFlgjfIbQxC8I4ZsTcANDFyioJEyA2jp0mBsZI-GOD-OY-fsvjoxZXBh_yaYTjVJIPUB0FC36BbnA"